/* ==========================================
 * TABLE: GCG_4662_DATA
 * ========================================== */
CREATE TABLE "GCG_4662_DATA"(
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "DEPARTMENT" LONGVARCHAR,
 "WORK_CENTER" LONGVARCHAR,
 "DISCREPANCY" LONGVARCHAR,
 "SCRAP_CODE" LONGVARCHAR,
 "VENDOR" LONGVARCHAR,
 "ACT_TYPE" CHAR(1),
 "DATE_CLOSED" DATE);


